stages:
    - trufflehog
    - snyk
    - build-frontend
    - push-frontend
    - build-backend
    - push-backend

# trufflehog_scan:
#   image: python:3
#   tags:
#     - docker-runner
#   stage: trufflehog
#   script:
#     - python3 -m venv venv
#     - source venv/bin/activate
#     - pip install truffleHog
#     - trufflehog --entropy=True --json /builds/anupamdutta/devops-fullstack-app > trufflehog_results.json
#   artifacts:
#     paths:
#       - trufflehog_results.json

# snyk:
#     image: node:14
#     tags:
#       - shell
#     stage: snyk
#     script:
#       - npm install -g snyk
#       - snyk auth $SNYK_TOKEN
#       - echo "running snyk test"
#       - snyk test --all-projects | tee snyk_report.txt
#       - echo "snyl test successful"
#     artifacts:
#       paths:
#         - snyk_report.txt
#     allow_failure: true

# frontend:
#     image: node:14
#     tags:
#       - docker-runner
#     stage: build-frontend
#     script:
#         - cd /builds/anupamdutta/devops-fullstack-app/frontend/
#         - npm install
#         - npm run build

push_frontend_image:
  image: alpine
  tags:
    - shell
  stage: push-frontend
  script:
      # - docker login -u anupamdutta -p $CI_REGISTRY_TOKEN code.techverito.com:4567
      - docker login -u anupam.dutta753 -p $GITLAB_TOKEN registry.gitlab.com
      - docker build -t registry.gitlab.com/anupam.dutta753/infrastructure/frontend -f Dockerfile-frontend .
      - docker push registry.gitlab.com/anupam.dutta753/infrastructure/frontend
      
# backend:
#     image: golang:1.19
#     tags:
#       - shell
#     stage: build-backend
#     script:
#         - cd /builds/anupam.dutta753/devops-fullstack-app/backend
#         - go mod download
#         - CGO_ENABLED=0 GOOS=linux go build -o app .
push_backend_image:
  image: alpine
  tags:
    - shell
  stage: push-backend
  script:
      # - docker login -u anupamdutta -p $CI_REGISTRY_TOKEN code.techverito.com:4567
      - docker login -u anupam.dutta753 -p $GITLAB_TOKEN registry.gitlab.com
      - docker build -t registry.gitlab.com/anupam.dutta753/infrastructure/backend -f Dockerfile-backend .
      - docker push registry.gitlab.com/anupam.dutta753/infrastructure/backend


      