# Build stage
FROM golang:1.19 AS builder

WORKDIR /app

# Clone the repository
RUN git clone https://github.com/anupamdevops321/source.git .

# Set working directory to the backend folder
WORKDIR /app/backend

# Download Go modules
RUN go mod download

# Build the Go binary
RUN CGO_ENABLED=0 GOOS=linux go build -o app .

# Production stage
FROM alpine:latest

WORKDIR /app


# Copy only necessary files from the builder stage
COPY --from=builder /app/backend/app .
COPY --from=builder /app/backend/go.mod .
COPY --from=builder /app/backend/go.sum .

# Expose the port
EXPOSE 8080

# Command to run the application
CMD ["./app"]
